"""Tests for scripts/commit_guard.py — the pre-push identity/attribution gate.

The rules come from AGENTS.md § Branches and Commits. They exist because the
harness presets GIT_AUTHOR_* but leaves GIT_COMMITTER_* empty, so any commit
written without explicit `-c user.*` flags silently takes the committer from
~/.gitconfig — and a rebase does that to every commit in the branch at once.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_SCRIPTS_DIR = _REPO_ROOT / "scripts"

# scripts/ is not a package — same import-path trick as test_agent_context.py.
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import commit_guard  # noqa: E402

GOOD = "Jane Doe <1234567+janedoe@users.noreply.github.com>"
BAD = "Claude <noreply@anthropic.com>"
SHA = "d8ea3450846abe5fdc26e88673ef659c4b400976"


# ── identity ─────────────────────────────────────────────────────────────────

def test_correct_identity_passes() -> None:
    assert commit_guard.check_commit(SHA, GOOD, GOOD, "fix(console): tidy") == []


def test_wrong_committer_is_reported() -> None:
    # The exact failure this hook exists for: `git rebase` without -c flags
    # keeps the author and rewrites only the committer.
    problems = commit_guard.check_commit(SHA, GOOD, BAD, "fix(console): tidy")
    assert len(problems) == 1
    assert "committer" in problems[0]
    assert BAD in problems[0]


def test_wrong_author_is_reported() -> None:
    problems = commit_guard.check_commit(SHA, BAD, GOOD, "fix(console): tidy")
    assert len(problems) == 1
    assert "author" in problems[0]


def test_both_identities_wrong_are_reported_separately() -> None:
    assert len(commit_guard.check_commit(SHA, BAD, BAD, "fix: x")) == 2


def test_private_email_is_reported() -> None:
    private = "Jane Doe <jane@gmail.com>"
    problems = commit_guard.check_commit(SHA, private, private, "fix: x")
    assert len(problems) == 2
    assert all("no-reply" in p or "noreply" in p for p in problems)


def test_author_and_committer_must_be_the_same_user() -> None:
    other = "John Roe <7654321+johnroe@users.noreply.github.com>"
    problems = commit_guard.check_commit(SHA, GOOD, other, "fix: x")
    assert len(problems) == 1
    assert "differs from author" in problems[0]


def test_report_names_the_offending_commit() -> None:
    problems = commit_guard.check_commit(SHA, GOOD, BAD, "fix: x")
    assert problems[0].startswith(SHA[:9])


# ── attribution ──────────────────────────────────────────────────────────────

@pytest.mark.parametrize("message", [
    "fix: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
    "fix: x\n\nco-authored-by: someone <a@b.c>",
    "fix: x\n\nClaude-Session: https://example.test/s/1",
    "fix: x\n\ncodex-session: abc",
    "fix: x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)",
    "fix: x\n\nGenerated by Codex.",
    "fix: x\n\nSee https://claude.ai/code/session_01",
])
def test_attribution_is_rejected(message: str) -> None:
    problems = commit_guard.check_commit(SHA, GOOD, GOOD, message)
    assert problems, f"should have been rejected: {message!r}"


@pytest.mark.parametrize("message", [
    # Ordinary prose must not trip the footer rule: the pattern requires a tool
    # name within 60 characters of "generated with/by".
    "feat(db): store the schema generated by the migration script",
    "fix(agent): drop the session trailer from the manifest parser",
    "refactor(console): rename ai_hint to hint",
    "test(console): run and expand the gui js suite",
])
def test_ordinary_messages_pass(message: str) -> None:
    assert commit_guard.check_commit(SHA, GOOD, GOOD, message) == []


# ── branch names ─────────────────────────────────────────────────────────────

@pytest.mark.parametrize("ref", [
    "refs/heads/claude/musubi-agent-orchestration-a1b93m",
    "refs/heads/feat/codex-port",
    "refs/heads/CLAUDE-scratch",
])
def test_tool_named_branches_are_rejected(ref: str) -> None:
    assert commit_guard.check_branch(ref)


@pytest.mark.parametrize("ref", [
    "refs/heads/fix/agent-advisory-scope-routing",
    "refs/heads/feat/console-request-runtime-history",
    "refs/heads/dev",
])
def test_product_named_branches_pass(ref: str) -> None:
    assert commit_guard.check_branch(ref) == []


# ── log parsing ──────────────────────────────────────────────────────────────

def test_parse_commits_survives_multiline_bodies() -> None:
    # A commit body wraps at 72 cols and contains blank lines; the parser must
    # not split on them, only on the record separator.
    record = (
        f"{SHA}\x1f{GOOD}\x1f{GOOD}\x1f"
        "feat(x): y\n\nbody line one\n\nbody line two\n\x1e"
    )
    commits = commit_guard.parse_commits(record)
    assert len(commits) == 1
    sha, author, committer, message = commits[0]
    assert (sha, author, committer) == (SHA, GOOD, GOOD)
    assert "body line two" in message


def test_parse_commits_handles_empty_output() -> None:
    assert commit_guard.parse_commits("") == []


# ── end to end, through a throwaway repository ───────────────────────────────

@pytest.fixture(autouse=True)
def _no_ambient_git_identity(monkeypatch: pytest.MonkeyPatch) -> None:
    # A harness may preset GIT_AUTHOR_* (cloud sessions use a private email), and
    # those win over the `-c user.*` flags these tests pass, so clear them.
    for var in ("GIT_AUTHOR_NAME", "GIT_AUTHOR_EMAIL", "GIT_COMMITTER_NAME", "GIT_COMMITTER_EMAIL"):
        monkeypatch.delenv(var, raising=False)


def _run_git(repo: Path, *args: str, env: dict | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, text=True, check=True, env=env,
    )


@pytest.fixture()
def repo_with_hook(tmp_path: Path) -> tuple[Path, Path]:
    """A repo whose pre-push hook is this repository's hook, plus a bare remote."""
    remote = tmp_path / "remote.git"
    subprocess.run(["git", "init", "--bare", "-q", str(remote)], check=True)

    work = tmp_path / "work"
    work.mkdir()
    _run_git(work, "init", "-q", "-b", "dev")
    _run_git(work, "remote", "add", "origin", str(remote))
    _run_git(work, "config", "core.hooksPath", str(_SCRIPTS_DIR / "git-hooks"))
    return work, remote


def _commit(repo: Path, text: str, *, name: str, email: str, message: str) -> None:
    (repo / "file.txt").write_text(text)
    _run_git(repo, "add", "file.txt")
    _run_git(
        repo,
        "-c", f"user.name={name}", "-c", f"user.email={email}",
        "commit", "-q", "-m", message,
    )


def _push(repo: Path, branch: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "push", "origin", branch],
        cwd=repo, capture_output=True, text=True,
    )


def test_hook_allows_a_clean_push(repo_with_hook: tuple[Path, Path]) -> None:
    work, _ = repo_with_hook
    _commit(work, "one", name="Jane Doe", email="1234567+janedoe@users.noreply.github.com", message="feat(x): add y")

    result = _push(work, "dev")

    assert result.returncode == 0, result.stderr


def test_hook_refuses_a_wrong_committer(repo_with_hook: tuple[Path, Path]) -> None:
    work, remote = repo_with_hook
    _commit(work, "one", name="Claude", email="noreply@anthropic.com", message="feat(x): add y")

    result = _push(work, "dev")

    assert result.returncode != 0
    assert "push refused" in result.stderr
    assert "committer" in result.stderr
    # The push must not have landed.
    assert _run_git(remote, "branch", "--list").stdout.strip() == ""


def test_hook_refuses_an_attribution_trailer(repo_with_hook: tuple[Path, Path]) -> None:
    work, _ = repo_with_hook
    _commit(
        work, "one",
        name="Jane Doe", email="1234567+janedoe@users.noreply.github.com",
        message="feat(x): add y\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
    )

    result = _push(work, "dev")

    assert result.returncode != 0
    assert "Co-Authored-By" in result.stderr


def test_hook_refuses_a_tool_named_branch(repo_with_hook: tuple[Path, Path]) -> None:
    work, _ = repo_with_hook
    _commit(work, "one", name="Jane Doe", email="1234567+janedoe@users.noreply.github.com", message="feat(x): add y")
    _run_git(work, "switch", "-q", "-c", "claude/scratch-1")

    result = _push(work, "claude/scratch-1")

    assert result.returncode != 0
    assert "names a tool" in result.stderr


def test_hook_checks_only_the_commits_being_pushed(repo_with_hook: tuple[Path, Path]) -> None:
    """A bad commit already on the remote must not block a later clean push.

    Without the remote_sha..local_sha range the hook would re-scan history on
    every push and permanently wedge the branch.
    """
    work, _ = repo_with_hook
    _commit(work, "one", name="Jane Doe", email="1234567+janedoe@users.noreply.github.com", message="feat(x): one")
    assert _push(work, "dev").returncode == 0

    # A commit that violates the rules, force-landed past the hook.
    _commit(work, "two", name="Claude", email="noreply@anthropic.com", message="feat(x): two")
    assert subprocess.run(
        ["git", "push", "--no-verify", "origin", "dev"],
        cwd=work, capture_output=True, text=True,
    ).returncode == 0

    _commit(work, "three", name="Jane Doe", email="1234567+janedoe@users.noreply.github.com", message="feat(x): three")

    result = _push(work, "dev")

    assert result.returncode == 0, result.stderr


def _commit_file(
    repo: Path, path: str, *, name: str, email: str, message: str,
) -> None:
    """Like `_commit`, but each commit touches its own file — so a rebase in
    the test exercises the guard rather than a merge conflict."""
    (repo / path).write_text(path)
    _run_git(repo, "add", path)
    _run_git(
        repo, "-c", f"user.name={name}", "-c", f"user.email={email}",
        "commit", "-q", "-m", message,
    )


def test_a_rebase_onto_a_moved_base_checks_only_the_rebased_commits(
    repo_with_hook: tuple[Path, Path],
) -> None:
    """The guard must not demand rewrites of commits the remote already has.

    `remote_sha..local_sha` looks like "what this push publishes" and is not:
    after a rebase, `remote_sha` is the branch's OLD head, so the range
    re-includes everything the new base brought in. In the real case that was a
    merge commit GitHub's web UI had authored on `dev` — the guard refused the
    push and asked for it to be rewritten, which cannot be done and must not be
    bypassed.
    """
    work, _ = repo_with_hook
    good = {"name": "Jane Doe", "email": "1234567+janedoe@users.noreply.github.com"}

    _commit_file(work, "base.txt", message="feat(x): base", **good)
    assert _push(work, "dev").returncode == 0

    _run_git(work, "checkout", "-q", "-b", "feat/thing")
    _commit_file(work, "mine.txt", message="feat(x): mine", **good)
    assert _push(work, "feat/thing").returncode == 0

    # Someone else lands a commit on dev with a foreign identity — a merge the
    # web UI authored, say. `--no-verify` stands in for "it arrived by some
    # route other than our hook". The guard is right to refuse such a commit on
    # a push of OURS; the point is what happens once it is already published.
    _run_git(work, "checkout", "-q", "dev")
    _commit_file(
        work, "theirs.txt", name="GitHub",
        email="noreply@github.com",
        message="Merge pull request #1 from somewhere",
    )
    assert subprocess.run(
        ["git", "push", "--no-verify", "origin", "dev"],
        cwd=work, capture_output=True, text=True,
    ).returncode == 0

    # Rebasing our branch onto it must still push.
    _run_git(work, "checkout", "-q", "feat/thing")
    _run_git(
        work, "-c", "user.name=Jane Doe",
        "-c", "user.email=1234567+janedoe@users.noreply.github.com",
        "rebase", "dev",
    )
    result = subprocess.run(
        ["git", "push", "--force-with-lease", "origin", "feat/thing"],
        cwd=work, capture_output=True, text=True,
    )

    assert result.returncode == 0, result.stderr
    assert "committer is" not in result.stderr and "author is" not in result.stderr


def test_a_bad_commit_of_ours_is_still_caught_after_a_rebase(
    repo_with_hook: tuple[Path, Path],
) -> None:
    # The narrower range must not become a hole: our own commits are still
    # checked, whatever the base did.
    work, _ = repo_with_hook
    _commit_file(work, "base.txt", name="Jane Doe",
                 email="1234567+janedoe@users.noreply.github.com", message="feat(x): base")
    assert _push(work, "dev").returncode == 0

    _run_git(work, "checkout", "-q", "-b", "feat/other")
    _commit_file(work, "mine.txt", name="Someone Else",
                 email="other@example.com", message="feat(x): mine")

    result = _push(work, "feat/other")

    assert result.returncode != 0
    assert "other@example.com" in result.stderr
